# Sidebar navigation

- label: 'Introducci√≥n'
  link: '/'
- label: 'Talleres'
  items:
    - label: 'Procesamiento de imagenes y videos por software'
      link: '/procesamiento'
    - label: 'Procesamiento de imagenes y videos por hardware'
      link: '/procesamiento2'
- label: 'Proyecto'
  items:
    - label: 'Propuesta'
      link: /proyecto/propuesta
    - label: 'Entregable'
      link: /proyecto/entregable